/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.11.26 at 10:54:28 AM EET
//

package com.codbex.kronos.parser.hdbcalculationview.ndb.bimodelcalculation;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for TopType.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="TopType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="rows"/&gt;
 *     &lt;enumeration value="sum"/&gt;
 *     &lt;enumeration value="percent"/&gt;
 *     &lt;enumeration value="first"/&gt;
 *     &lt;enumeration value="last"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "TopType")
@XmlEnum
public enum TopType {

    /** The rows. */
    @XmlEnumValue("rows") ROWS("rows"),

    /** The sum. */
    @XmlEnumValue("sum") SUM("sum"),

    /** The percent. */
    @XmlEnumValue("percent") PERCENT("percent"),

    /** The first. */
    @XmlEnumValue("first") FIRST("first"),

    /** The last. */
    @XmlEnumValue("last") LAST("last");

    /** The value. */
    private final String value;

    /**
     * Instantiates a new top type.
     *
     * @param v the v
     */
    TopType(String v) {
        value = v;
    }

    /**
     * From value.
     *
     * @param v the v
     * @return the top type
     */
    public static TopType fromValue(String v) {
        for (TopType c : TopType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return value;
    }

}
