/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getTemplate() {
	return {
		name: "ABAP Starter",
		description: "ABAP Starter Template",
		sources: [{
			location: "/template-abap/abap_transpile.json",
			action: "generate",
			rename: "abap_transpile.json"
		},{
			location: "/template-abap/abaplint.json",
			action: "generate",
			rename: "abaplint.json"
		},{
			location: "/template-abap/build-linux.sh",
			action: "generate",
			rename: "build-linux.sh"
		},{
			location: "/template-abap/build-mac.sh",
			action: "generate",
			rename: "build-mac.sh"
		},{
			location: "/template-abap/package.json",
			action: "generate",
			rename: "package.json"
		},{
			location: "/template-abap/project.json",
			action: "generate",
			rename: "project.json"
		},{
			location: "/template-abap/tsconfig.json",
			action: "generate",
			rename: "tsconfig.json"
		},{
			location: "/template-abap/src/abap/zcl_abap_app.clas.abap",
			action: "generate",
			rename: "src/abap/zcl_abap_app.clas.abap"
		},{
			location: "/template-abap/src/lib/polyfills/buffer.js",
			action: "generate",
			rename: "src/lib/polyfills/buffer.js"
		},{
			location: "/template-abap/src/lib/polyfills/process.js",
			action: "generate",
			rename: "src/lib/polyfills/process.js"
		},{
      location: "/template-abap/src/run.mjs",
      action: "generate",
      rename: "src/run.mjs"
    }],
		parameters: [],
		order: 30
	};
};
