/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.11.26 at 10:54:28 AM EET
//

package com.codbex.kronos.parser.hdbcalculationview.ndb.basemodelbase;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for CycleHandling.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="CycleHandling"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BREAKUP"/&gt;
 *     &lt;enumeration value="TRAVERSE_COMPLETELY"/&gt;
 *     &lt;enumeration value="ERROR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "CycleHandling")
@XmlEnum
public enum CycleHandling {

    /**
     * (break up at load time): This is the default for new and old models. Cycles are broken up at load
     * time. They might be traversed incompletely if starting from within a cycle and not from the root
     * node. Which node is marked with IS_CYCLE = 1 depends on the initial traversal during the
     * hierarchy instantiation.
     */
    BREAKUP,

    /**
     * (Traverse completely, then break up): Cycles are completely traversed once and then broken up.
     * The duplicate node is marked with IS_CYCLE = 1 in the result
     */
    TRAVERSE_COMPLETELY,

    /** Error in case the hierarchy navigation traverses a cycle. */
    ERROR;

    /**
     * From value.
     *
     * @param v the v
     * @return the cycle handling
     */
    public static CycleHandling fromValue(String v) {
        return valueOf(v);
    }

    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return name();
    }

}
