/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.codbex.kronos.ndb.datamodelgraph;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * Java class for GraphAction.
 *
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;simpleType name="GraphAction"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="PATTERN_MATCHING"/&gt;
 *     &lt;enumeration value="SCRIPT_PATTERN_MATCHING"/&gt;
 *     &lt;enumeration value="GET_NEIGHBORHOOD"/&gt;
 *     &lt;enumeration value="GET_SHORTEST_PATHS_ONE_TO_ALL"/&gt;
 *     &lt;enumeration value="GET_SHORTEST_PATHS_ONE_TO_ONE"/&gt;
 *     &lt;enumeration value="GET_STRONGLY_CONNECTED_COMPONENTS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "GraphAction")
@XmlEnum
public enum GraphAction {

  /** The pattern matching. */
  PATTERN_MATCHING,
  
  /** The script pattern matching. */
  SCRIPT_PATTERN_MATCHING,
  
  /** The get neighborhood. */
  GET_NEIGHBORHOOD,
  
  /** The get shortest paths one to all. */
  GET_SHORTEST_PATHS_ONE_TO_ALL,
  
  /** The get shortest paths one to one. */
  GET_SHORTEST_PATHS_ONE_TO_ONE,
  
  /** The get strongly connected components. */
  GET_STRONGLY_CONNECTED_COMPONENTS;

  /**
   * From value.
   *
   * @param v the v
   * @return the graph action
   */
  public static GraphAction fromValue(String v) {
    return valueOf(v);
  }

  /**
   * Value.
   *
   * @return the string
   */
  public String value() {
    return name();
  }

}
