FROM tomcat:9.0.56-jre11-openjdk AS base

RUN rm -R /usr/local/tomcat/webapps.dist
COPY target/ROOT.war $CATALINA_HOME/webapps/

RUN wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.1.4/postgresql-42.1.4.jar -P /usr/local/tomcat/lib/
RUN wget https://repo1.maven.org/maven2/com/sap/cloud/db/jdbc/ngdbc/2.8.12/ngdbc-2.8.12.jar -P /usr/local/tomcat/lib/

RUN mkdir -p /usr/local/tomcat/target/dirigible/repository/root/registry/public/

FROM sapmachine:17.0.2 as jdk

COPY --from=base /usr/local/tomcat /usr/local/tomcat
