/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.codbex.kronos.ndb.bimodelcalculation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.codbex.kronos.ndb.datamodelhierarchy.HierarchyAncestorsParameterization;
import com.codbex.kronos.ndb.datamodelhierarchy.HierarchyDescendantsParameterization;
import com.codbex.kronos.ndb.datamodelhierarchy.HierarchyFunction;
import com.codbex.kronos.ndb.datamodelhierarchy.HierarchyLeveledParameterization;
import com.codbex.kronos.ndb.datamodelhierarchy.HierarchyParameterization;
import com.codbex.kronos.ndb.datamodelhierarchy.HierarchySiblingsParameterization;
import com.codbex.kronos.ndb.datamodelhierarchy.HierarchySpanTreeParameterization;
import com.codbex.kronos.ndb.datamodelhierarchy.HierarchyTemporalParameterization;


/**
 * A View node for hierarchy generation functions and navigation functions.
 *
 *
 * Java class for HierarchyView complex type.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="HierarchyView"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sap.com/ndb/BiModelCalculation.ecore}CalculationView"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="hierarchyParameterization" type="{http://www.sap.com/ndb/DataModelHierarchy.ecore}HierarchyParameterization"/&gt;
 *         &lt;element name="hierarchyLeveledParameterization" type="{http://www.sap.com/ndb/DataModelHierarchy.ecore}HierarchyLeveledParameterization"/&gt;
 *         &lt;element name="hierarchyTemporalParameterization" type="{http://www.sap.com/ndb/DataModelHierarchy.ecore}hierarchyTemporalParameterization"/&gt;
 *         &lt;element name="hierarchySpanTreeParameterization" type="{http://www.sap.com/ndb/DataModelHierarchy.ecore}HierarchySpanTreeParameterization"/&gt;
 *         &lt;element name="hierarchyDescendantsParameterization" type="{http://www.sap.com/ndb/DataModelHierarchy.ecore}HierarchyDescendantsParameterization"/&gt;
 *         &lt;element name="hierarchyAncestorsParameterization" type="{http://www.sap.com/ndb/DataModelHierarchy.ecore}HierarchyAncestorsParameterization"/&gt;
 *         &lt;element name="hierarchySiblingsParameterization" type="{http://www.sap.com/ndb/DataModelHierarchy.ecore}HierarchySiblingsParameterization"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="function" type="{http://www.sap.com/ndb/DataModelHierarchy.ecore}HierarchyFunction" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HierarchyView", propOrder = {
    "hierarchyParameterization",
    "hierarchyLeveledParameterization",
    "hierarchyTemporalParameterization",
    "hierarchySpanTreeParameterization",
    "hierarchyDescendantsParameterization",
    "hierarchyAncestorsParameterization",
    "hierarchySiblingsParameterization"
})
public class HierarchyView
    extends CalculationView {

  /** The hierarchy parameterization. */
  protected HierarchyParameterization hierarchyParameterization;
  
  /** The hierarchy leveled parameterization. */
  protected HierarchyLeveledParameterization hierarchyLeveledParameterization;
  
  /** The hierarchy temporal parameterization. */
  protected HierarchyTemporalParameterization hierarchyTemporalParameterization;
  
  /** The hierarchy span tree parameterization. */
  protected HierarchySpanTreeParameterization hierarchySpanTreeParameterization;
  
  /** The hierarchy descendants parameterization. */
  protected HierarchyDescendantsParameterization hierarchyDescendantsParameterization;
  
  /** The hierarchy ancestors parameterization. */
  protected HierarchyAncestorsParameterization hierarchyAncestorsParameterization;
  
  /** The hierarchy siblings parameterization. */
  protected HierarchySiblingsParameterization hierarchySiblingsParameterization;
  
  /** The function. */
  @XmlAttribute(name = "function")
  protected HierarchyFunction function;

  /**
   * Gets the value of the hierarchyParameterization property.
   *
   * @return possible object is
   * {@link HierarchyParameterization }
   */
  public HierarchyParameterization getHierarchyParameterization() {
    return hierarchyParameterization;
  }

  /**
   * Sets the value of the hierarchyParameterization property.
   *
   * @param value allowed object is
   *              {@link HierarchyParameterization }
   */
  public void setHierarchyParameterization(HierarchyParameterization value) {
    this.hierarchyParameterization = value;
  }

  /**
   * Gets the value of the hierarchyLeveledParameterization property.
   *
   * @return possible object is
   * {@link HierarchyLeveledParameterization }
   */
  public HierarchyLeveledParameterization getHierarchyLeveledParameterization() {
    return hierarchyLeveledParameterization;
  }

  /**
   * Sets the value of the hierarchyLeveledParameterization property.
   *
   * @param value allowed object is
   *              {@link HierarchyLeveledParameterization }
   */
  public void setHierarchyLeveledParameterization(HierarchyLeveledParameterization value) {
    this.hierarchyLeveledParameterization = value;
  }

  /**
   * Gets the value of the hierarchyTemporalParameterization property.
   *
   * @return possible object is
   * {@link HierarchyTemporalParameterization }
   */
  public HierarchyTemporalParameterization getHierarchyTemporalParameterization() {
    return hierarchyTemporalParameterization;
  }

  /**
   * Sets the value of the hierarchyTemporalParameterization property.
   *
   * @param value allowed object is
   *              {@link HierarchyTemporalParameterization }
   */
  public void setHierarchyTemporalParameterization(HierarchyTemporalParameterization value) {
    this.hierarchyTemporalParameterization = value;
  }

  /**
   * Gets the value of the hierarchySpanTreeParameterization property.
   *
   * @return possible object is
   * {@link HierarchySpanTreeParameterization }
   */
  public HierarchySpanTreeParameterization getHierarchySpanTreeParameterization() {
    return hierarchySpanTreeParameterization;
  }

  /**
   * Sets the value of the hierarchySpanTreeParameterization property.
   *
   * @param value allowed object is
   *              {@link HierarchySpanTreeParameterization }
   */
  public void setHierarchySpanTreeParameterization(HierarchySpanTreeParameterization value) {
    this.hierarchySpanTreeParameterization = value;
  }

  /**
   * Gets the value of the hierarchyDescendantsParameterization property.
   *
   * @return possible object is
   * {@link HierarchyDescendantsParameterization }
   */
  public HierarchyDescendantsParameterization getHierarchyDescendantsParameterization() {
    return hierarchyDescendantsParameterization;
  }

  /**
   * Sets the value of the hierarchyDescendantsParameterization property.
   *
   * @param value allowed object is
   *              {@link HierarchyDescendantsParameterization }
   */
  public void setHierarchyDescendantsParameterization(HierarchyDescendantsParameterization value) {
    this.hierarchyDescendantsParameterization = value;
  }

  /**
   * Gets the value of the hierarchyAncestorsParameterization property.
   *
   * @return possible object is
   * {@link HierarchyAncestorsParameterization }
   */
  public HierarchyAncestorsParameterization getHierarchyAncestorsParameterization() {
    return hierarchyAncestorsParameterization;
  }

  /**
   * Sets the value of the hierarchyAncestorsParameterization property.
   *
   * @param value allowed object is
   *              {@link HierarchyAncestorsParameterization }
   */
  public void setHierarchyAncestorsParameterization(HierarchyAncestorsParameterization value) {
    this.hierarchyAncestorsParameterization = value;
  }

  /**
   * Gets the value of the hierarchySiblingsParameterization property.
   *
   * @return possible object is
   * {@link HierarchySiblingsParameterization }
   */
  public HierarchySiblingsParameterization getHierarchySiblingsParameterization() {
    return hierarchySiblingsParameterization;
  }

  /**
   * Sets the value of the hierarchySiblingsParameterization property.
   *
   * @param value allowed object is
   *              {@link HierarchySiblingsParameterization }
   */
  public void setHierarchySiblingsParameterization(HierarchySiblingsParameterization value) {
    this.hierarchySiblingsParameterization = value;
  }

  /**
   * Gets the value of the function property.
   *
   * @return possible object is
   * {@link HierarchyFunction }
   */
  public HierarchyFunction getFunction() {
    return function;
  }

  /**
   * Sets the value of the function property.
   *
   * @param value allowed object is
   *              {@link HierarchyFunction }
   */
  public void setFunction(HierarchyFunction value) {
    this.function = value;
  }

}
