/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getTemplate() {
	return {
		"name": "XSJS Import API",
		"description": "XSJS Import API Template",
		"sources": [{
			"location": "/template-xsjs-import/service.xsjs.template", 
			"action": "generate",
			"rename": "{{fileName}}.xsjs"
		},{
			"location": "/template-xsjs-import/lib/math.xsjslib", 
			"action": "copy",
			"rename": "lib/math.xsjslib"
		}],
		"parameters": [],
		"order": 20
	};
};
