/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function() {
	return {
		"name": "HDB Table",
		"description": "HDB Table Template",
		"sources": [
		{
			"location": "/template-hdbtable/hdb.schema.template", 
			"action": "generate",
			"rename": "{{schemaName}}.hdbschema"
		},{
			"location": "/template-hdbtable/hdb.table.template", 
			"action": "generate",
			"rename": "{{tableName}}.hdbtable"
		}],
		"parameters": [
		{
			"name": "schemaName",
			"label": "Schema Name"
		},{
			"name": "tableName",
			"label": "Table Name"
		}],
		"order": 10
	};
};
