/*
 * Copyright (c) 2022-2023 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.codbex.kronos.parser.hdbcalculationview.ndb.bimodeldatafoundation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.codbex.kronos.parser.hdbcalculationview.ndb.bimodelcube.MeasureGroup;
import com.codbex.kronos.parser.hdbcalculationview.ndb.bimodeldimension.Dimension;


/**
 * Common base for objects having attributes and data foundations
 *
 *
 * Java class for LogicalObject complex type.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LogicalObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sap.com/ndb/BiModelDataFoundation.ecore}InformationModel"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="attributes" type="{http://www.sap.com/ndb/BiModelDataFoundation.ecore}Attributes" minOccurs="0"/&gt;
 *         &lt;element name="calculatedAttributes" type="{http://www.sap.com/ndb/BiModelDataFoundation.ecore}CalculatedAttributes" minOccurs="0"/&gt;
 *         &lt;element name="allAttributes" type="{http://www.sap.com/ndb/BiModelDataFoundation.ecore}AbstractAttribute" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="privateDataFoundation" type="{http://www.sap.com/ndb/BiModelDataFoundation.ecore}DataFoundation" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogicalObject", propOrder = {
    "attributes",
    "calculatedAttributes",
    "allAttributes",
    "privateDataFoundation"
})
@XmlSeeAlso({
    MeasureGroup.class,
    Dimension.class
})
public class LogicalObject
    extends InformationModel {

  /** The attributes. */
  protected Attributes attributes;
  
  /** The calculated attributes. */
  protected CalculatedAttributes calculatedAttributes;
  
  /** The all attributes. */
  protected List<AbstractAttribute> allAttributes;
  
  /** The private data foundation. */
  protected DataFoundation privateDataFoundation;

  /**
   * Gets the value of the attributes property.
   *
   * @return possible object is
   * {@link Attributes }
   */
  public Attributes getAttributes() {
    return attributes;
  }

  /**
   * Sets the value of the attributes property.
   *
   * @param value allowed object is
   *              {@link Attributes }
   */
  public void setAttributes(Attributes value) {
    this.attributes = value;
  }

  /**
   * Gets the value of the calculatedAttributes property.
   *
   * @return possible object is
   * {@link CalculatedAttributes }
   */
  public CalculatedAttributes getCalculatedAttributes() {
    return calculatedAttributes;
  }

  /**
   * Sets the value of the calculatedAttributes property.
   *
   * @param value allowed object is
   *              {@link CalculatedAttributes }
   */
  public void setCalculatedAttributes(CalculatedAttributes value) {
    this.calculatedAttributes = value;
  }

  /**
   * Gets the value of the allAttributes property.
   * 
   * 
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the allAttributes property.
   * 
   * 
   * For example, to add a new item, do as follows:
   * <pre>
   *    getAllAttributes().add(newItem);
   * </pre>
   * 
   * 
   * 
   * Objects of the following type(s) are allowed in the list
   * {@link AbstractAttribute }
   *
   * @return the all attributes
   */
  public List<AbstractAttribute> getAllAttributes() {
    if (allAttributes == null) {
      allAttributes = new ArrayList<AbstractAttribute>();
    }
    return this.allAttributes;
  }

  /**
   * Gets the value of the privateDataFoundation property.
   *
   * @return possible object is
   * {@link DataFoundation }
   */
  public DataFoundation getPrivateDataFoundation() {
    return privateDataFoundation;
  }

  /**
   * Sets the value of the privateDataFoundation property.
   *
   * @param value allowed object is
   *              {@link DataFoundation }
   */
  public void setPrivateDataFoundation(DataFoundation value) {
    this.privateDataFoundation = value;
  }

}
