/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.codbex.kronos.parser.hdbcalculationview.ndb.basemodelbase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Specification of hierarchy join properties.
 *
 *
 * Java class for HierarchyJoinProperties complex type.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="HierarchyJoinProperties"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="nodeElementName" type="{http://www.sap.com/ndb/BaseModelBase.ecore}DbName" /&gt;
 *       &lt;attribute name="levelElementName" type="{http://www.sap.com/ndb/BaseModelBase.ecore}DbName" /&gt;
 *       &lt;attribute name="ordinalElementName" type="{http://www.sap.com/ndb/BaseModelBase.ecore}DbName" /&gt;
 *       &lt;attribute name="expressionParameterName" type="{http://www.sap.com/ndb/BaseModelBase.ecore}DbName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HierarchyJoinProperties")
public class HierarchyJoinProperties {

  /** The node element name. */
  @XmlAttribute(name = "nodeElementName")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String nodeElementName;
  
  /** The level element name. */
  @XmlAttribute(name = "levelElementName")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String levelElementName;
  
  /** The ordinal element name. */
  @XmlAttribute(name = "ordinalElementName")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String ordinalElementName;
  
  /** The expression parameter name. */
  @XmlAttribute(name = "expressionParameterName")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String expressionParameterName;

  /**
   * Gets the value of the nodeElementName property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getNodeElementName() {
    return nodeElementName;
  }

  /**
   * Sets the value of the nodeElementName property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setNodeElementName(String value) {
    this.nodeElementName = value;
  }

  /**
   * Gets the value of the levelElementName property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getLevelElementName() {
    return levelElementName;
  }

  /**
   * Sets the value of the levelElementName property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setLevelElementName(String value) {
    this.levelElementName = value;
  }

  /**
   * Gets the value of the ordinalElementName property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getOrdinalElementName() {
    return ordinalElementName;
  }

  /**
   * Sets the value of the ordinalElementName property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setOrdinalElementName(String value) {
    this.ordinalElementName = value;
  }

  /**
   * Gets the value of the expressionParameterName property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getExpressionParameterName() {
    return expressionParameterName;
  }

  /**
   * Sets the value of the expressionParameterName property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setExpressionParameterName(String value) {
    this.expressionParameterName = value;
  }

}
