/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.11.26 at 10:54:28 AM EET
//

package com.codbex.kronos.parser.hdbcalculationview.ndb.basemodelbase;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for LevelType.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="LevelType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_REGULAR"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_ALL"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_CALCULATED"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_YEARS"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_HALF_YEAR"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_QUARTERS"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_MONTHS"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_WEEKS"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_DAYS"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_HOURS"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_MINUTES"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_SECONDS"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_TIME_UNDEFINED"/&gt;
 *     &lt;enumeration value="MDLEVEL_TYPE_UNKNOWN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "LevelType")
@XmlEnum
public enum LevelType {

    /** The mdlevel type regular. */
    MDLEVEL_TYPE_REGULAR,

    /** The mdlevel type all. */
    MDLEVEL_TYPE_ALL,

    /** The mdlevel type calculated. */
    MDLEVEL_TYPE_CALCULATED,

    /** The mdlevel type time. */
    MDLEVEL_TYPE_TIME,

    /** The mdlevel type time years. */
    MDLEVEL_TYPE_TIME_YEARS,

    /** The mdlevel type time half year. */
    MDLEVEL_TYPE_TIME_HALF_YEAR,

    /** The mdlevel type time quarters. */
    MDLEVEL_TYPE_TIME_QUARTERS,

    /** The mdlevel type time months. */
    MDLEVEL_TYPE_TIME_MONTHS,

    /** The mdlevel type time weeks. */
    MDLEVEL_TYPE_TIME_WEEKS,

    /** The mdlevel type time days. */
    MDLEVEL_TYPE_TIME_DAYS,

    /** The mdlevel type time hours. */
    MDLEVEL_TYPE_TIME_HOURS,

    /** The mdlevel type time minutes. */
    MDLEVEL_TYPE_TIME_MINUTES,

    /** The mdlevel type time seconds. */
    MDLEVEL_TYPE_TIME_SECONDS,

    /** The mdlevel type time undefined. */
    MDLEVEL_TYPE_TIME_UNDEFINED,

    /** The mdlevel type unknown. */
    MDLEVEL_TYPE_UNKNOWN;

    /**
     * From value.
     *
     * @param v the v
     * @return the level type
     */
    public static LevelType fromValue(String v) {
        return valueOf(v);
    }

    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return name();
    }

}
