/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function() {
	return {
		"name": "XSJS Hello World",
		"description": "XSJS Hello World Template",
		"sources": [{
			"location": "/template-xsjs/service.xsjs.template", 
			"action": "generate",
			"rename": "{{fileName}}.xsjs"
		}],
		"parameters": [],
		"order": -1
	};
};
