/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.codbex.kronos.parser.hdbcalculationview.ndb.bimodelcalculation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.codbex.kronos.parser.hdbcalculationview.ndb.repositorymodelresource.IDObjectWithDescription;


/**
 * Java class for Node complex type.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Node"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sap.com/ndb/RepositoryModelResource.ecore}IDObjectWithDescription"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="viewAttributes" type="{http://www.sap.com/ndb/BiModelCalculation.ecore}ViewAttributes" minOccurs="0"/&gt;
 *         &lt;element name="calculatedViewAttributes" type="{http://www.sap.com/ndb/BiModelCalculation.ecore}CalculatedViewAttributes" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Node", propOrder = {
    "viewAttributes",
    "calculatedViewAttributes"
})
@XmlSeeAlso({
    DataSource.class,
    GraphView.class,
    CalculationView.class
})
public abstract class Node
    extends IDObjectWithDescription {

  /** The view attributes. */
  protected ViewAttributes viewAttributes;
  
  /** The calculated view attributes. */
  protected CalculatedViewAttributes calculatedViewAttributes;

  /**
   * Gets the value of the viewAttributes property.
   *
   * @return possible object is
   * {@link ViewAttributes }
   */
  public ViewAttributes getViewAttributes() {
    return viewAttributes;
  }

  /**
   * Sets the value of the viewAttributes property.
   *
   * @param value allowed object is
   *              {@link ViewAttributes }
   */
  public void setViewAttributes(ViewAttributes value) {
    this.viewAttributes = value;
  }

  /**
   * Gets the value of the calculatedViewAttributes property.
   *
   * @return possible object is
   * {@link CalculatedViewAttributes }
   */
  public CalculatedViewAttributes getCalculatedViewAttributes() {
    return calculatedViewAttributes;
  }

  /**
   * Sets the value of the calculatedViewAttributes property.
   *
   * @param value allowed object is
   *              {@link CalculatedViewAttributes }
   */
  public void setCalculatedViewAttributes(CalculatedViewAttributes value) {
    this.calculatedViewAttributes = value;
  }

}
