/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.11.26 at 10:54:28 AM EET
//

package com.codbex.kronos.parser.hdbcalculationview.ndb.repositorymodelresource;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.codbex.kronos.parser.hdbcalculationview.ndb.basemodelbase.EndUserTexts;
import com.codbex.kronos.parser.hdbcalculationview.ndb.datamodeltype.DataType;

/**
 * Father object for EMF repository objects. The resource aspects of ResourceObject have been
 * removed from this to separate concerns
 *
 *
 * Java class for RepositoryObject complex type.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RepositoryObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sap.com/ndb/RepositoryModelResource.ecore}AbstractRepositoryObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="endUserTexts" type="{http://www.sap.com/ndb/BaseModelBase.ecore}EndUserTexts" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.sap.com/ndb/RepositoryModelResource.ecore}Identifier" /&gt;
 *       &lt;attribute name="nameQualifier" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="deprecated" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepositoryObject", propOrder = {"endUserTexts"})
@XmlSeeAlso({DataType.class})
public abstract class RepositoryObject extends AbstractRepositoryObject {

    /** The end user texts. */
    protected EndUserTexts endUserTexts;

    /** The name. */
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;

    /** The name qualifier. */
    @XmlAttribute(name = "nameQualifier")
    protected String nameQualifier;

    /** The deprecated. */
    @XmlAttribute(name = "deprecated")
    protected Boolean deprecated;

    /**
     * Gets the value of the endUserTexts property.
     *
     * @return possible object is {@link EndUserTexts }
     */
    public EndUserTexts getEndUserTexts() {
        return endUserTexts;
    }

    /**
     * Sets the value of the endUserTexts property.
     *
     * @param value allowed object is {@link EndUserTexts }
     */
    public void setEndUserTexts(EndUserTexts value) {
        this.endUserTexts = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameQualifier property.
     *
     * @return possible object is {@link String }
     */
    public String getNameQualifier() {
        return nameQualifier;
    }

    /**
     * Sets the value of the nameQualifier property.
     *
     * @param value allowed object is {@link String }
     */
    public void setNameQualifier(String value) {
        this.nameQualifier = value;
    }

    /**
     * Gets the value of the deprecated property.
     *
     * @return possible object is {@link Boolean }
     */
    public Boolean isDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     *
     * @param value allowed object is {@link Boolean }
     */
    public void setDeprecated(Boolean value) {
        this.deprecated = value;
    }

}
