/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function() {
	return {
		"name": "HDBDD",
		"description": "HDBDD Template",
		"sources": [
		{
			"location": "/template-hdbdd/hdb.schema.template", 
			"action": "generate",
			"rename": "{{schemaName}}.hdbschema"
		},{
			"location": "/template-hdbdd/hdbdd.template", 
			"action": "generate",
			"rename": "{{fileName}}.hdbdd"
		}],
		"parameters": [
		{
			"name": "schemaName",
			"label": "Schema Name"
		},{
			"name": "contextName",
			"label": "Context Name"
		},{
			"name": "entityName",
			"label": "Entity Name"
		}],
		"order": 10
	};
};
