/*
 * Copyright (c) 2022 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.11.26 at 10:54:28 AM EET
//

package com.codbex.kronos.parser.hdbcalculationview.ndb.datamodelhierarchy;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Specification of time dependent columns and parameters.
 *
 *
 * Java class for HierarchyTimeProperties complex type.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="HierarchyTimeProperties"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="validFromElement" type="{http://www.sap.com/ndb/RepositoryModelResource.ecore}Identifier"/&gt;
 *         &lt;element name="validToElement" type="{http://www.sap.com/ndb/RepositoryModelResource.ecore}Identifier"/&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="fromParameter" type="{http://www.sap.com/ndb/RepositoryModelResource.ecore}Identifier"/&gt;
 *             &lt;element name="toParameter" type="{http://www.sap.com/ndb/RepositoryModelResource.ecore}Identifier"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="pointInTimeParameter" type="{http://www.sap.com/ndb/RepositoryModelResource.ecore}Identifier"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HierarchyTimeProperties",
        propOrder = {"validFromElement", "validToElement", "fromParameter", "toParameter", "pointInTimeParameter"})
public class HierarchyTimeProperties {

    /** The valid from element. */
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String validFromElement;

    /** The valid to element. */
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String validToElement;

    /** The from parameter. */
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String fromParameter;

    /** The to parameter. */
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String toParameter;

    /** The point in time parameter. */
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String pointInTimeParameter;

    /**
     * Gets the value of the validFromElement property.
     *
     * @return possible object is {@link String }
     */
    public String getValidFromElement() {
        return validFromElement;
    }

    /**
     * Sets the value of the validFromElement property.
     *
     * @param value allowed object is {@link String }
     */
    public void setValidFromElement(String value) {
        this.validFromElement = value;
    }

    /**
     * Gets the value of the validToElement property.
     *
     * @return possible object is {@link String }
     */
    public String getValidToElement() {
        return validToElement;
    }

    /**
     * Sets the value of the validToElement property.
     *
     * @param value allowed object is {@link String }
     */
    public void setValidToElement(String value) {
        this.validToElement = value;
    }

    /**
     * Gets the value of the fromParameter property.
     *
     * @return possible object is {@link String }
     */
    public String getFromParameter() {
        return fromParameter;
    }

    /**
     * Sets the value of the fromParameter property.
     *
     * @param value allowed object is {@link String }
     */
    public void setFromParameter(String value) {
        this.fromParameter = value;
    }

    /**
     * Gets the value of the toParameter property.
     *
     * @return possible object is {@link String }
     */
    public String getToParameter() {
        return toParameter;
    }

    /**
     * Sets the value of the toParameter property.
     *
     * @param value allowed object is {@link String }
     */
    public void setToParameter(String value) {
        this.toParameter = value;
    }

    /**
     * Gets the value of the pointInTimeParameter property.
     *
     * @return possible object is {@link String }
     */
    public String getPointInTimeParameter() {
        return pointInTimeParameter;
    }

    /**
     * Sets the value of the pointInTimeParameter property.
     *
     * @param value allowed object is {@link String }
     */
    public void setPointInTimeParameter(String value) {
        this.pointInTimeParameter = value;
    }

}
