name: Build - Platform

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: codbex/codbex-infra/.github/workflows/platform-build.yaml@main
    with:
      platform-name: codbex-kronos
      docker-build: true
      oras_repos: 'ghcr.io/codbex/codbex-bw-migration/codbex-abap-bw:latest'
    secrets: inherit
