name: Build - Platform

on:
  push:
    branches:
      - main
      - dg8

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-build.yaml@main
    with:
      platform-name: codbex-kronos
    secrets: inherit