name: "DAST Scan with OWASP ZAP [Push & PR]"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  dast_zap_scan:
    runs-on: ubuntu-latest

    services:
      application:
        image: ghcr.io/codbex/codbex-kronos:latest
        ports:
          - 80:80
        options: >-
          --health-cmd "curl -f http://localhost:80/actuator/health/readiness || exit 1"
          --health-interval 10s
          --health-timeout 120s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for App to Start
        run: |
          echo "Waiting for the app to be ready..."
          sleep 30  # Adjust based on startup time

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:80'
          cmd_options: '-a -T 5 -j -r' # https://www.zaproxy.org/docs/docker/full-scan/
          artifact_name: dast_zap_report
          docker_name: 'owasp/zap2docker-stable'
          allow_issue_writing: true

      - name: Upload ZAP Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dast_zap_report
          path: dast_zap_report.html
