name: Docker image scanner [Anchore]

on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string
        default: ghcr.io/codbex/codbex-kronos
      tag:
        required: true
        type: string
        default: latest

run-name: 'Scan image [${{ inputs.image }}] tag [${{ inputs.tag }}]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Scan Image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ inputs.image }}:${{ inputs.tag }}
          fail-build: true
          output-format: sarif

      - name: Upload Anchore Scan SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

