name: Pre-release

on:
  push:
    tags:
    - 'pre*'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      KRONOS_VERSION_BUILD: ${{ steps.KRONOS_VERSION_PRINT.outputs.KRONOS_VERSION_OUTPUT }}
      KRONOS_HELM_SHA: ${{ steps.KRONOS_HELM_SHA.outputs.KRONOS_HELM_SHA_PRINT }}
    steps:
    #--------Restore success job-------#
    - name: Previous succeeded job
      id: success
      uses: actions/cache@v3
      with:
          path: success-job-${{ github.sha }}-${{ matrix.name }}
          key: success-job-job-${{ github.sha }}-${{ matrix.name }}
    #--------Restore success job-------# 
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: Download sapmachine JDK 17
      run: |
        download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.2/sapmachine-jdk-17.0.2_linux-x64_bin.tar.gz"
        wget -O "${RUNNER_TEMP}/sapmachine-jdk-17.tar.gz" "${download_url}"
    - name: Setup sapmachine JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/sapmachine-jdk-17.tar.gz
        java-version: '17.0.2'
        architecture: x64
    - name: Set Kronos Version
      run: echo KRONOS_VERSION=${GITHUB_REF#refs/*/} | tr pre " " | sed 's/   //'  >> $GITHUB_ENV
    - name: KRONOS_VERSION_OUTPUT
      run: echo "::set-output name=KRONOS_VERSION_OUTPUT::$KRONOS_VERSION"
      id: KRONOS_VERSION_PRINT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
    - name: Set Multi-Builder Docker Buildx
      run: docker buildx create --use --name multi-builder --platform linux/arm64,linux/amd64
    - name: Maven Build
      run: mvn clean install
    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Push Kronos
      run: |
        cd releng/server
        cp -r "${JAVA_HOME}" jdk
        docker build --load -t ghcr.io/codbex/kronos:${{ env.KRONOS_VERSION }} --build-arg JDK_TYPE=external-jdk --build-arg JDK_HOME=jdk .
        docker push ghcr.io/codbex/kronos:${{ env.KRONOS_VERSION }}
        cd ../../
    - name: Push Kronos for SAP Cloud Foundry
      run: |
        cd releng/sap-cf
        cp -r "${JAVA_HOME}" jdk
        docker build --load -t ghcr.io/codbex/kronos-cf:${{ env.KRONOS_VERSION }} --build-arg JDK_TYPE=external-jdk --build-arg JDK_HOME=jdk .
        docker push ghcr.io/codbex/kronos-cf:${{ env.KRONOS_VERSION }}
        cd ../../
    - name: Push Kronos for SAP Kyma
      run: |
        cd releng/sap-kyma
        cp -r "${JAVA_HOME}" jdk
        docker build --load -t ghcr.io/codbex/kronos-kyma:${{ env.KRONOS_VERSION }} --build-arg JDK_TYPE=external-jdk --build-arg JDK_HOME=jdk .
        docker push ghcr.io/codbex/kronos-kyma:${{ env.KRONOS_VERSION }}
        cd ../../
    - name: Push Kronos for SAP Kyma Runtime
      run: |
        cd releng/sap-kyma-runtime
        docker build --load -t ghcr.io/codbex/kronos-kyma-runtime-base -f Dockerfile-base .
        docker push ghcr.io/codbex/kronos-kyma-runtime-base
        docker build --load -t ghcr.io/codbex/kronos-kyma-runtime .
        docker push ghcr.io/codbex/kronos-kyma-runtime
        docker build --load -t ghcr.io/codbex/kronos-kyma-runtime-distro -f Dockerfile-distro .
        docker push ghcr.io/codbex/kronos-kyma-runtime-distro
        cd ../../
    # - uses: buildpacks/github-actions/setup-pack@v4.1.0
    # - name: Kronos Buildpack
    #   run: |
    #     cd releng/buildpacks/kronos/
    #     docker build --load --build-arg KRONOS_VERSION=${{ env.KRONOS_VERSION }} -t ghcr.io/codbex/kronos-buildpacks-stack-base . --target base
    #     docker tag ghcr.io/codbex/kronos-buildpacks-stack-base ghcr.io/codbex/kronos-buildpacks-stack-base:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-base:${{ env.KRONOS_VERSION }}
    #     docker build --load --build-arg KRONOS_VERSION=${{ env.KRONOS_VERSION }} -t ghcr.io/codbex/kronos-buildpacks-stack-run . --target run
    #     docker tag ghcr.io/codbex/kronos-buildpacks-stack-run ghcr.io/codbex/kronos-buildpacks-stack-run:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-run:${{ env.KRONOS_VERSION }}
    #     docker build --load --build-arg KRONOS_VERSION=${{ env.KRONOS_VERSION }} -t ghcr.io/codbex/kronos-buildpacks-stack-build . --target build
    #     docker tag ghcr.io/codbex/kronos-buildpacks-stack-build ghcr.io/codbex/kronos-buildpacks-stack-build:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-build:${{ env.KRONOS_VERSION }}
    #     cd buildpack/
    #     find *.toml -type f -exec sed -i ''s/#{KronosVersion}#/${{ env.KRONOS_VERSION }}/g'' {} \;
    #     pack buildpack package ghcr.io/codbex/kronos-buildpacks --config ./package.toml
    #     docker tag ghcr.io/codbex/kronos-buildpacks ghcr.io/codbex/kronos-buildpacks:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks:${{ env.KRONOS_VERSION }}
    #     pack builder create ghcr.io/codbex/kronos-buildpacks-builder --config ./builder.toml
    #     docker tag ghcr.io/codbex/kronos-buildpacks-builder ghcr.io/codbex/kronos-buildpacks-builder:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-builder:${{ env.KRONOS_VERSION }}
    #     cd ../../../../
    # - name: Kronos Kyma Buildpack
    #   run: |
    #     cd releng/buildpacks/kronos-kyma/
    #     docker build --load --build-arg KRONOS_VERSION=${{ env.KRONOS_VERSION }} -t ghcr.io/codbex/kronos-buildpacks-stack-base-kyma . --target base
    #     docker tag ghcr.io/codbex/kronos-buildpacks-stack-base-kyma ghcr.io/codbex/kronos-buildpacks-stack-base-kyma:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-base-kyma:${{ env.KRONOS_VERSION }}
    #     docker build --load --build-arg KRONOS_VERSION=${{ env.KRONOS_VERSION }} -t ghcr.io/codbex/kronos-buildpacks-stack-run-kyma . --target run
    #     docker tag ghcr.io/codbex/kronos-buildpacks-stack-run-kyma ghcr.io/codbex/kronos-buildpacks-stack-run-kyma:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-run-kyma:${{ env.KRONOS_VERSION }}
    #     docker build --load --build-arg KRONOS_VERSION=${{ env.KRONOS_VERSION }} -t ghcr.io/codbex/kronos-buildpacks-stack-build-kyma . --target build
    #     docker tag ghcr.io/codbex/kronos-buildpacks-stack-build-kyma ghcr.io/codbex/kronos-buildpacks-stack-build-kyma:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-build-kyma:${{ env.KRONOS_VERSION }}
    #     cd buildpack/
    #     find *.toml -type f -exec sed -i ''s/#{KronosVersion}#/${{ env.KRONOS_VERSION }}/g'' {} \;
    #     pack buildpack package ghcr.io/codbex/kronos-buildpacks-kyma --config ./package.toml
    #     docker tag ghcr.io/codbex/kronos-buildpacks-kyma ghcr.io/codbex/kronos-buildpacks-kyma:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-kyma:${{ env.KRONOS_VERSION }}
    #     pack builder create ghcr.io/codbex/kronos-buildpacks-builder-kyma --config ./builder.toml
    #     docker tag ghcr.io/codbex/kronos-buildpacks-builder-kyma ghcr.io/codbex/kronos-buildpacks-builder-kyma:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-builder-kyma:${{ env.KRONOS_VERSION }}
    #     cd ../../../../
    # - name: Kronos Kyma Runtime Buildpack
    #   run: |
    #     cd releng/buildpacks/kronos-kyma-runtime/
    #     docker build --load -t ghcr.io/codbex/kronos-buildpacks-stack-base-kyma-runtime . --target base
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-base-kyma-runtime
    #     docker build --load -t ghcr.io/codbex/kronos-buildpacks-stack-run-kyma-runtime . --target run
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-run-kyma-runtime
    #     docker build --load -t ghcr.io/codbex/kronos-buildpacks-stack-build-kyma-runtime . --target build
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-build-kyma-runtime
    #     cd buildpack/
    #     find *.toml -type f -exec sed -i ''s/#{KronosVersion}#/latest/g'' {} \;
    #     pack buildpack package ghcr.io/codbex/kronos-buildpacks-kyma-runtime --config ./package.toml
    #     docker push ghcr.io/codbex/kronos-buildpacks-kyma-runtime
    #     pack builder create ghcr.io/codbex/kronos-buildpacks-builder-kyma-runtime --config ./builder.toml
    #     docker push ghcr.io/codbex/kronos-buildpacks-builder-kyma-runtime
    #     cd ../../../../
    # - name: Kronos Cloud Foundry Buildpack
    #   run: |
    #     cd releng/buildpacks/kronos-cf/
    #     docker build --load --build-arg KRONOS_VERSION=${{ env.KRONOS_VERSION }} -t ghcr.io/codbex/kronos-buildpacks-stack-base-cf . --target base
    #     docker tag ghcr.io/codbex/kronos-buildpacks-stack-base-cf ghcr.io/codbex/kronos-buildpacks-stack-base-cf:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-base-cf:${{ env.KRONOS_VERSION }}
    #     docker build --load --build-arg KRONOS_VERSION=${{ env.KRONOS_VERSION }} -t ghcr.io/codbex/kronos-buildpacks-stack-run-cf . --target run
    #     docker tag ghcr.io/codbex/kronos-buildpacks-stack-run-cf ghcr.io/codbex/kronos-buildpacks-stack-run-cf:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-run-cf:${{ env.KRONOS_VERSION }}
    #     docker build --load --build-arg KRONOS_VERSION=${{ env.KRONOS_VERSION }} -t ghcr.io/codbex/kronos-buildpacks-stack-build-cf . --target build
    #     docker tag ghcr.io/codbex/kronos-buildpacks-stack-build-cf ghcr.io/codbex/kronos-buildpacks-stack-build-cf:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-stack-build-cf:${{ env.KRONOS_VERSION }}
    #     cd buildpack/
    #     find *.toml -type f -exec sed -i ''s/#{KronosVersion}#/${{ env.KRONOS_VERSION }}/g'' {} \;
    #     pack buildpack package ghcr.io/codbex/kronos-buildpacks-cf --config ./package.toml
    #     docker tag ghcr.io/codbex/kronos-buildpacks-cf ghcr.io/codbex/kronos-buildpacks-cf:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-cf:${{ env.KRONOS_VERSION }}
    #     pack builder create ghcr.io/codbex/kronos-buildpacks-builder-cf --config ./builder.toml
    #     docker tag ghcr.io/codbex/kronos-buildpacks-builder-cf ghcr.io/codbex/kronos-buildpacks-builder-cf:${{ env.KRONOS_VERSION }}
    #     docker push ghcr.io/codbex/kronos-buildpacks-builder-cf:${{ env.KRONOS_VERSION }}
    #     cd ../../../../

#----------------Helm Release------------------#
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.GPG_KEY_HELM }}") | gpg --batch --import  --no-tty --batch --yes
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
    - name: Helm Charts Release - Checkout gh-pages
      run: |
        mkdir charts-temp
        cp -r releng/helm-charts/ charts-temp/
        #### Git Checkout Workaround
        git add .github/
        git add .reuse/
        git add LICENSES/
        git add modules/
        git add releng/
        git add samples/
        git reset --hard
        ####
        git fetch
        git checkout gh-pages
        cp charts/* .        
    - name: Helm Charts Release - Set Chart Version - Kronos
      run: |
        cd charts-temp/helm-charts/
        find kronos/*.yaml -type f -exec sed -i ''s/#{KronosVersion}#/${{ env.KRONOS_VERSION }}/g'' {} \;
        find kronos-kpack/*.yaml -type f -exec sed -i ''s/#{KronosVersion}#/${{ env.KRONOS_VERSION }}/g'' {} \;
        find kronos-kpack/templates/*.yaml -type f -exec sed -i ''s/#{KronosVersion}#/${{ env.KRONOS_VERSION }}/g'' {} \;
        find kronos-landscape/*.yaml -type f -exec sed -i ''s/#{KronosVersion}#/${{ env.KRONOS_VERSION }}/g'' {} \;
    - name: Helm Charts Release
      run: |
        cp charts/* charts-temp/helm-charts/
        cd charts-temp/helm-charts/
          
        gpg --no-tty --batch --export-secret-keys > ~/.gnupg/secring.gpg
        helm package --sign --key "Kronos-gpg" --keyring /home/runner/.gnupg/secring.gpg kronos
        helm package --sign --key "Kronos-gpg" --keyring /home/runner/.gnupg/secring.gpg kronos-kpack
        helm package --sign --key "Kronos-gpg" --keyring /home/runner/.gnupg/secring.gpg kronos-landscape        
    - name: Verify helm chart
      run: |
        wget https://codbex.com/charts/pubring.gpg -O ~/.gnupg/pubring.gpg
        cd charts-temp/helm-charts/
        OUTPUT=$(helm verify --keyring ~/.gnupg/pubring.gpg kronos-${{ env.KRONOS_VERSION }}.tgz)
        OUTPUT="${OUTPUT//'%'/'%25'}"
        OUTPUT="${OUTPUT//$'\n'/'%0A'}"
        OUTPUT="${OUTPUT//$'\r'/'%0D'}"
        HELM_SHA=$(echo "$OUTPUT" | tail -n1)
        SHA=$(sed -e 's#.*sha256:\(\)#\1#' <<< $HELM_SHA )
        echo "::set-output name=KRONOS_HELM_SHA_PRINT::$SHA"
      id: KRONOS_HELM_SHA
    - name: Helm Chart Release Index
      run: |
        cd charts-temp/
        helm repo index helm-charts/ --url https://codbex.github.io/codbex-kronos/charts
        cp -rf helm-charts/index.yaml ../.
        cp -rf helm-charts/kronos-${{ env.KRONOS_VERSION }}.tgz ../charts/
        cp -rf helm-charts/kronos-${{ env.KRONOS_VERSION }}.tgz.prov ../charts/
        cp -rf helm-charts/kronos-kpack-${{ env.KRONOS_VERSION }}.tgz ../charts/
        cp -rf helm-charts/kronos-kpack-${{ env.KRONOS_VERSION }}.tgz.prov ../charts/
        cp -rf helm-charts/kronos-landscape-${{ env.KRONOS_VERSION }}.tgz ../charts/
        cp -rf helm-charts/kronos-landscape-${{ env.KRONOS_VERSION }}.tgz.prov ../charts/
        cd ..
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add index.yaml
        git add charts/
        git commit -m "Updates Helm Charts - Release ${{ env.KRONOS_VERSION }} - ci skip"
        git push origin gh-pages
        git add .
        git reset --hard
        git checkout main

    - name: Slack Notification
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.14.0
      with:
        payload: "{\"type\":\"Pre-release\",\"url\":\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  Stage-release:
      needs: build 
      uses: ./.github/workflows/stage-release.yaml
      with:
        KRONOS_VERSION: ${{ needs.build.outputs.KRONOS_VERSION_BUILD }}
        KRONOS_HELM_SHA: ${{ needs.build.outputs.KRONOS_HELM_SHA }}
        KRONOS_DISPATCH: 'false'
      secrets:
        STAGE_KYMA_CONFIG: ${{ secrets.STAGE_KYMA_CONFIG }}
        STAGE_HANA_URL: ${{ secrets.STAGE_HANA_URL }}
        STAGE_HANA_USERNAME: ${{ secrets.STAGE_HANA_USERNAME }}
        STAGE_HANA_PASSWORD: ${{ secrets.STAGE_HANA_PASSWORD }}
        STAGE_KYMA_HOST: ${{ secrets.STAGE_KYMA_HOST }}
        STAGE_NAMESPACE: ${{ secrets.STAGE_NAMESPACE }}
        STAGE_SERVICE_ACCOUNT: ${{ secrets.STAGE_SERVICE_ACCOUNT }}
