name: "Generate Security Report"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '32 20 * * 0'

jobs:
  generate-security-report:
    steps:
      - name: Generate Security Report
        uses: rsdmike/github-security-report-action@v3.0.4
        with:
          token: ${{ secrets.SECURITY_TOKEN }}
