name: Stage-release

on:
  workflow_dispatch:
    inputs:
      KRONOS_VERSION:
        description: 'Kronos version'
        required: true
  workflow_call:
    inputs:
      KRONOS_VERSION:
        required: true
        type: string
      KRONOS_HELM_SHA:
        required: true
        type: string
      KRONOS_DISPATCH:
        required: true
        type: string
    secrets:
      STAGE_KYMA_CONFIG:
        required: true
      STAGE_HANA_URL:
        required: true
      STAGE_HANA_USERNAME:
        required: true
      STAGE_HANA_PASSWORD:
        required: true
      STAGE_KYMA_HOST:
        required: true
      STAGE_NAMESPACE:
        required: true
      STAGE_SERVICE_ACCOUNT:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #------Restore previous job---------#
    - name: Composer cache
      if: steps.success.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
    - run : echo "done" > success-job-${{ github.sha }}-${{ matrix.name }}
    #--------Restore previous job-------#
    # Set Kronos Kyma context 
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.STAGE_KYMA_CONFIG }}

    # Install helm
    - uses: azure/setup-helm@v1
      with:
        version: 'latest' # default is latest stable
      id: install

    # Add repo
    - name: Add Kronos helm repo
      run: |
        helm repo add kronos https://codbex.github.io/codbex-kronos
        helm repo update
        mkdir ~/.gnupg
        wget https://codbex.com/charts/pubring.gpg -O ~/.gnupg/pubring.gpg

    # Check chart sha and set Kronos version
    - name: Check and set Kronos version
      uses: nick-fields/retry@v2
      with:
        timeout_seconds: 5
        max_attempts: 10
        retry_on: error
        command: |          
          if [[ ! -z "${{ inputs.KRONOS_DISPATCH }}" ]] 
          then
              OUTPUT=$(helm pull kronos/kronos --version ${{ inputs.KRONOS_VERSION }} --verify)
              OUTPUT="${OUTPUT//'%'/'%25'}"
              OUTPUT="${OUTPUT//$'\n'/'%0A'}"
              OUTPUT="${OUTPUT//$'\r'/'%0D'}"
              HELM_SHA=$(echo "$OUTPUT" | tail -n1)
              SHA=$(sed -e 's#.*sha256:\(\)#\1#' <<< $HELM_SHA)
              if [ $SHA != ${{ inputs.KRONOS_HELM_SHA }} ]
                then
                  echo "Failed to verify sha!"
                  exit 1
              fi
              echo "::set-output name=KRONOS_VERSION_OUTPUT::${{ inputs.KRONOS_VERSION }}"
          else 
            helm pull kronos/kronos --version ${{ github.event.inputs.KRONOS_VERSION }} --verify
            KRONOS_VERSION=${{ github.event.inputs.KRONOS_VERSION }}
            echo "::set-output name=KRONOS_VERSION_OUTPUT::$KRONOS_VERSION"
          fi
      id: KRONOS_VERSION

    # Deploy Kronos on stage
    - name: Deploy Kronos helm chart
      run: |
        KRONOS_VERSION="${{ steps.KRONOS_VERSION.outputs.KRONOS_VERSION_OUTPUT }}"
        helm upgrade --install kronos-stage kronos/kronos --version $KRONOS_VERSION -n ${{ secrets.STAGE_NAMESPACE }} \
        --set hana.enabled=true \
        --set hana.url="jdbc:sap://${{ secrets.STAGE_HANA_URL }}/?encrypt=true&validateCertificate=false" \
        --set hana.username=${{ secrets.STAGE_HANA_USERNAME }} \
        --set hana.password=${{ secrets.STAGE_HANA_PASSWORD }} \
        --set kyma.enabled=true \
        --set kyma.host=${{ secrets.STAGE_KYMA_HOST }} \
        --set serviceAccount.name=${{ secrets.STAGE_SERVICE_ACCOUNT }} \
        --set application.image=ghcr.io/codbex/kronos-kyma:$KRONOS_VERSION

    # Wait for Kronos Service Container to Startup
    - name: Wait Kronos Startup
      uses: nick-invision/retry@v2
      with:
        timeout_seconds: 15
        max_attempts: 15
        warning_on_retry: false
        command: curl -m 5 --silent --fail --request GET https://${{ secrets.STAGE_NAMESPACE }}.${{ secrets.STAGE_KYMA_HOST }}/services/v4/healthcheck | jq --exit-status -n 'inputs | if has("status") then .status=="Ready" else false end' > /dev/null
